### ISSUE TITLE
Some cases with 'nan' for max and min values

### ISSUE THREAD

**Issue by ellesmith88** [roocs/character-scanner-test#13]

**Comment by agstephens** [comment]
@ellesmith88: here is another useful issue to look at. If you can find an example of a NaN then it would be good for us to take a look into why it is happening.

**Comment by ellesmith88** [comment]
The data at /badc/cmip5/data/cmip5/output1/MOHC/HadGEM2-ES/historical/mon/land/Lmon/r1i1p1/latest/rh produces NaNs for the maximum and minimum of its data values. I'll have a look at the data again for this one.

**Comment by ellesmith88** [comment]
NaNs are missing values filled in by xarray. To mask them:
`ds = xr.open_mfdataset('/badc/cmip5/data/cmip5/output1/MOHC/HadGEM2-ES/historical/mon/land/Lmon/r1i1p1/latest/rh/*.nc', combine='by_coords')masked_data = ds.rh.to_masked_array(copy=False)
mx = masked_data.max()
mn = masked_data.min()`

**Comment by ellesmith88** [comment]
@agstephens Not fixed in version 0.15. Found that different methods give different results. 

If done in this way:
`data = ds.rh.values`
`mx = data.max()`
the result is still NaN.

If extracted in this way:
`mx = float(ds.rh.max())`
the result is the same as with using the masked array.

**Comment by agstephens** [comment]
Done.
